// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA86-2megLXCAukn8gdnGOLN_BeFyqVHzo',
    appId: '1:555396008452:web:3033116c4bf6e691048351',
    messagingSenderId: '555396008452',
    projectId: 'shopapp-a9f42',
    authDomain: 'shopapp-a9f42.firebaseapp.com',
    storageBucket: 'shopapp-a9f42.firebasestorage.app',
    measurementId: 'G-CVN8MBQ3KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCVjrkCPpggreTSh6y1-oXWA6z68KWRiU',
    appId: '1:555396008452:android:fa611ac99f79b5c8048351',
    messagingSenderId: '555396008452',
    projectId: 'shopapp-a9f42',
    storageBucket: 'shopapp-a9f42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTY97bGeii59hyXmEqnAz9beWroN7uNEE',
    appId: '1:555396008452:ios:34f8c183e9f8fc3f048351',
    messagingSenderId: '555396008452',
    projectId: 'shopapp-a9f42',
    storageBucket: 'shopapp-a9f42.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTY97bGeii59hyXmEqnAz9beWroN7uNEE',
    appId: '1:555396008452:ios:34f8c183e9f8fc3f048351',
    messagingSenderId: '555396008452',
    projectId: 'shopapp-a9f42',
    storageBucket: 'shopapp-a9f42.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA86-2megLXCAukn8gdnGOLN_BeFyqVHzo',
    appId: '1:555396008452:web:86080935a63cb3a3048351',
    messagingSenderId: '555396008452',
    projectId: 'shopapp-a9f42',
    authDomain: 'shopapp-a9f42.firebaseapp.com',
    storageBucket: 'shopapp-a9f42.firebasestorage.app',
    measurementId: 'G-70LCYHNP6Y',
  );
}
